---
title: "Mauvais genre"
format:
  html: 
    embed-resources: true
editor: source
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, 
               warning = FALSE, 
               error = FALSE,
               message = FALSE)

```

```{r packages}
library(targets)
library(tidyverse)
library(here)
source(here("R", "common_functions.R"))
set_ggplot_options()
```

# Data and Methods

```{r}
#| label: data
tar_load(artists_filtered, store = "../_targets/")
```


```{r}
#| label: PCA
library(FactoMineR)
library(factoextra)
pca_mod <- compute_pca(artists_filtered)
fviz_pca_var(pca_mod)
ggsave("pca_var.pdf", path = here("output", "omni1"), device="pdf")
```


# Results


```{r}
#| label: gg_endoexoleg_bygenre
#| fig-height: 6
tar_load(gg_endoexoleg_bygenre, store = "../_targets/")
print(gg_endoexoleg_bygenre)
ggsave("gg_endoexoleg_bygenre.pdf", gg_endoexoleg_bygenre, path = here("output", "omni1"), device = "pdf")
```

```{r}
#| label: gg_endoexoleg_bygenre_mean_errorbar

tar_load(gg_endoexoleg_bygenre_mean_errorbar, store = "../_targets/")
print(gg_endoexoleg_bygenre_mean_errorbar)
ggsave("gg_endoexoleg_bygenre_mean_errorbar.pdf", gg_endoexoleg_bygenre_mean_errorbar, path = here("output", "omni1"), device = "pdf")
```


```{r}
#| label: gg_endoexoleg_genrerank
tar_load(gg_endoexoleg_genrerank, store = "../_targets/")
print(gg_endoexoleg_genrerank)
ggsave("gg_endoexoleg_genrerank.pdf", gg_endoexoleg_genrerank, path = here("output", "omni1"), device = "pdf")
```


```{r}
#| label: gg_endoexoleg_correlation
#| fig-height: 6
tar_load(gg_endoexoleg_correlation, store = "../_targets/")
print(gg_endoexoleg_correlation)
ggsave("gg_endoexoleg_correlation.pdf", gg_endoexoleg_correlation, path = here("output", "omni1"), device = "pdf")
```

```{r}
#| label: gg_endoexoleg_correlation_genremean
#| fig-height: 6
tar_load(gg_endoexoleg_correlation_genremean, store = "../_targets/")
print(gg_endoexoleg_correlation_genremean)
ggsave("gg_endoexoleg_correlation_genremean.pdf", gg_endoexoleg_correlation_genremean, path = here("output", "omni1"), device = "pdf")
```


```{r}
#| label: gg_endoexoleg_correlation_bygenre
#| fig-height: 9
tar_load(gg_endoexoleg_correlation_bygenre, store = "../_targets/")
print(gg_endoexoleg_correlation_bygenre)
ggsave("gg_endoexoleg_correlation_bygenre.pdf", gg_endoexoleg_correlation_bygenre, path = here("output", "omni1"), device = "pdf")
```

```{r}
#| label: gg_endoexoleg_correlation_bygenre_pres
#| fig-height: 6
#| fig-width: 10
tar_load(gg_endoexoleg_correlation_bygenre_pres, store = "../_targets/")
print(gg_endoexoleg_correlation_bygenre_pres)
ggsave("gg_endoexoleg_correlation_bygenre_pres.pdf", gg_endoexoleg_correlation_bygenre_pres, path = here("output", "omni1"), device = "pdf")
```


```{r}
#| label: tb_leg_variance
tar_load(tb_leg_variance, store = "../_targets/")
kable(tb_leg_variance)
```


We use the measure of overlap proposed by https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2019.01089/full

```{r}
#| label: overlap
#| fig-height: 6
#gg_genre_overlap
tar_load(gg_genre_overlap, store = "../_targets/")
print(gg_genre_overlap)
ggsave("gg_genre_overlap.pdf", gg_genre_overlap, path = here("output", "omni1"), device="pdf")

```

```{r}
#| label: example overlap
#| height: 6
artists_filtered %>% 
  filter(genre %in% c("frenchrap", "rock")) %>% 
  mutate(genre = recode_vars(genre, "genres")) %>% 
  ggplot(aes(sc_endo_isei, fill = genre)) +
    geom_density(alpha=.5) +
    labs(y = "Density", x = "Endogenous legitimacy (ISEI)", fill = "")
ggsave("example_overlap.pdf", path = here("output", "omni1"), device = "pdf")
    
```


# Exploration

# Supplements

## Distribution of all variables considered for legitimacy

```{r}
#| label: gg_endoleg_bygenre
#| fig-height: 6
tar_load(gg_endoleg_bygenre, store = "../_targets/")
gg_endoleg_bygenre
ggsave("gg_endoleg_bygenre.pdf", gg_endoleg_bygenre, path = here("output", "omni1"), device = "pdf")
```

```{r}
#| label: gg_exoleg_bygenre
#| fig-height: 9
tar_load(gg_exoleg_bygenre, store = "../_targets/")
gg_exoleg_bygenre
ggsave("gg_exoleg_bygenre.pdf", gg_exoleg_bygenre, path = here("output", "omni1"), device = "pdf")
```