# options(repos="https://stat.ethz.ch/CRAN/")
install.packages("GGally")
install.packages("tidytable")
install.packages("visNetwork")
install.packages("tarchetypes")
install.packages("here")
# ## Dependencies for FactoMineR
install.packages("pbkrtest")
install.packages("lme4")
install.packages("car")
install.packages("rstatix")
install.packages("ggpubr")
install.packages("FactoMineR")
install.packages("factoextra")
install.packages("ggrepel")
install.packages("overlapping")
install.packages("gghalves")
install.packages("mclust")
install.packages("poLCA")
install.packages("WikidataQueryServiceR")
install.packages("janitor")
install.packages("quanteda")
install.packages("spacyr")
install.packages("foreach")
install.packages("doParallel")
# library(usethis)
# create_project(path = "mauvaisgenre", open = FALSE, rstudio = TRUE)
# library(targets)
# tar_make()
