---
title: "Mauvais genre"
format: 
  html:
    embed-resources: true
editor: source
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, 
               warning = FALSE, 
               error = FALSE,
               message = FALSE)

```

```{r packages}
library(targets)
library(tidyverse)
source("R/common_functions.R")
```

# Data and Methods

```{r}
#| label: data
tar_load(artists_filtered)
```


```{r}
#| label: PCA
library(FactoMineR)
library(factoextra)
pca_mod <- compute_pca(artists_filtered)
fviz_pca_var(pca_mod)
```


# Results

```{r}
#| label: gg_endoleg_bygenre
tar_load(gg_endoleg_bygenre)
gg_endoleg_bygenre
```

```{r}
#| label: gg_exoleg_bygenre
tar_load(gg_exoleg_bygenre)
gg_exoleg_bygenre
```

```{r}
#| label: gg_endoexoleg_bygenre
tar_load(gg_endoexoleg_bygenre)
print(gg_endoexoleg_bygenre)

```


```{r}
#| label: gg_endoexoleg_correlation
tar_load(gg_endoexoleg_correlation)
print(gg_endoexoleg_correlation)
```

```{r}
#| label: gg_endoexoleg_correlation_genremean
tar_load(gg_endoexoleg_correlation_genremean)
print(gg_endoexoleg_correlation_genremean)
```


```{r}
#| label: gg_endoexoleg_correlation_bygenre
tar_load(gg_endoexoleg_correlation_bygenre)
print(gg_endoexoleg_correlation_bygenre)
```

```{r}
#| label: tb_leg_variance
tar_load(tb_leg_variance)
kable(tb_leg_variance)
```

# Exploration

```{r}
x <- artists_filtered %>% 
  select(genre, starts_with("sc")) %>% 
  pivot_longer(-genre) %>% 
  filter(!is.na(value)) %>% 
  group_by(genre, name) %>% 
  summarize(m = mean(value)) %>% 
  arrange(name, desc(m)) %>% 
  group_by(name) %>% 
  mutate(rank = row_number()) %>% 
  select(-m) %>% 
  pivot_wider(names_from = name, values_from = rank)

kable(x)
```

```{r}
y <- x %>% 
  mutate(endo = (sc_endo_educ + sc_endo_isei)/2,
         exo  = (sc_exo_press + sc_exo_score)/2) %>% 
  select(genre, endo, exo) %>% 
  arrange(endo) %>% 
  mutate(diff = endo-exo)
kable(y)
```


```{r}
artists_filtered %>% 
  filter(radio_total > 100) %>% 
  mutate(radio_ratio = radio_leg / radio_total) %>% 
  group_by(genre) %>% 
  summarize(m = mean(radio_ratio)) %>% 
  arrange(desc(m)) %>% 
  kable() 
  
```

# Overlap between genres.

```{r}
# Pairwise cohen's d
# cohen d = (x_1-x_2)/s ou s = pooled sd
# s = \sqrt(((n1-1)s1^2+n2-1*s2^2)/n1+n2-2)
x1 <- artists_filtered %>% 
  group_by(genre) %>% 
  summarise(m1 = mean(endo_isei_mean_pond),
            v1 = var(endo_isei_mean_pond),
            n1 = n())
x2 <- x1 %>% rename(genre2 = "genre", 
                    m2="m1",
                    v2="v1",
                    n2="n1")
options(scipen = 99)
l <- vector("list", length = nrow(x1))
names(l) <- x1$genre
for(ge in x1$genre){
  l[[ge]] <- filter(x1, genre == ge) %>% 
    bind_cols(x2) %>% 
    mutate(d = abs((m1-m2))/sqrt(((n1-1)*v1+(n2-1)*v2)/(n1+n2-2))) %>% 
    select(genre, genre2, d)
}
bind_rows(l) %>% 
  mutate(d=round(d, 2)) %>% 
  group_by(genre) %>% 
  mutate(m = mean(d)) %>% 
  ungroup() %>% 
  mutate(genre = factor(genre) %>% fct_reorder(d, mean),
         genre2 = factor(genre2, levels = levels(genre))) %>% 
  ggplot(aes(genre, genre2, fill=d, label=d)) +
    geom_tile() +
    geom_text() +
    theme(axis.text.x = element_text(angle=90, hjust=1,vjust=0.5))

```

